version: '3.8'

services:
  web:
    build: .
    container_name: likhit_web
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - FLASK_ENV=development
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_USER=likhit
      - MYSQL_PASSWORD=likhit123
      - MYSQL_DB=likhit_db

  db:
    image: mysql:8.0
    container_name: likhit_db
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: likhit_db
      MYSQL_USER: likhit
      MYSQL_PASSWORD: likhit123
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
